name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: dbname
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    - name: Set up database URL
      run: echo "DATABASE_URL=postgres://user:password@localhost/dbname" >> $GITHUB_ENV
      working-directory: ./chatapp_backend
    - name: Install sqlx-cli
      run: cargo install sqlx-cli
      working-directory: ./chatapp_backend
    - name: Run migrations
      run: cargo sqlx migrate run
      working-directory: ./chatapp_backend
    - name: Build
      run: cargo build --verbose
      working-directory: ./chatapp_backend
    - name: Run tests
      run: cargo test --verbose
      working-directory: ./chatapp_backend
    - name: Prepare SQLx
      run: cargo sqlx prepare
      working-directory: ./chatapp_backend
